name: to_string_gen
description: GEN for to_string
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: '>=0.12.0 < 2.0.0'
  source_gen: ^0.9.0
  to_string:
    path: ../to_string/

dev_dependencies:
  build_test: ^0.10.0
  build_runner: ^1.10.0
  test: ^1.0.0
  analyzer: ^0.39.8
