name: to_string
description: Collect All field And genarate toString();
version: 0.0.1
homepage: http://www.wenmq.cn


environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

dev_dependencies:
  test: 1.3.4


